### ISSUE TITLE
Setting the game?

### ISSUE THREAD

**Issue by sword134** [ukgamer/gmod-arcademachines#52] opened 2021-01-26 11:34 UTC
Hello,
I just installed the addon and everytime I spawn in the arcade machine it says "NO GAME LOADED", so I've looked through the files but I cant see anyfield in which you can specify the game?

**Comment by henkeswe** [comment] 2021-01-26 18:37
Right now you have to call it through Lua, SV: Entity:SetCurrentGame("game")

**Comment by sword134** [comment] 2021-01-26 18:38
@henkeswe is there a way to do it automatically on server start?

**Comment by ukgamer** [comment] 2021-01-26 18:41
Currently you need to do this as the cabinet was initially intended to be spawned via Lua as part of a system that populates the map with Lua entities.

A "launcher" is on my to do list so that when you spawn a cabinet you have a way of selecting a game to load without needing to use Lua.

You could create a serverside autorun script that creates the entity and calls ent:SetCurrentGame("asteroids") etc.

Created an issue for this #53

**Comment by sword134** [comment] 2021-01-26 18:53
@ukgamer hmmm, do you have an example of such a file?

**Comment by ukgamer** [comment] 2021-01-26 19:14
Not tested, but something like this should work (placed in lua/autorun/server/spawn_cabinet.lua):

```lua
local cab = ents.Create("arcade_cabinet")
cab:SetPos(Vector(100, 100, 100))
cab:Spawn()
cab:SetCurrentGame("asteroids")
```

**Comment by sword134** [comment] 2021-01-26 22:01
@ukgamer I tried pasting the above code and replacing the vector with what I got from the getpos command in console. Nothing spawned.

**Comment by ukgamer** [comment] 2021-01-26 22:35
Try placing it within an InitPostEntity hook (and then reload the map/server)

**Comment by sword134** [comment] 2021-01-26 23:14
@ukgamer here is my code currently (it still doesn't spawn in) and yes its in the correct folders

```
function SpawnEntityCabinet()
	local cab = ents.Create("arcade_cabinet")
	cab:SetPos(Vector(1268.745728, -144.634567, 24.896152))
	cab:Spawn()
	cab:SetCurrentGame("asteroids")
end
hook.Add( "InitPostEntity", "SpawnEntityCabinet", SpawnEntityCabinet)
```

**Comment by ukgamer** [comment] 2021-01-26 23:51
That code works for me when it's placed in garrysmod/lua/autorun/server/spawntest.lua when running a local server.

**Comment by sword134** [comment] 2021-01-26 23:52
@ukgamer perhaps I am using the wrong vector? Can you explain which and how you get the vector values?

**Comment by sword134** [comment] 2021-01-27 00:00
@ukgamer ok I got it to work. For some reason there was an indentation error

**Comment by ukgamer** [comment] 2021-01-27 00:01
Glad you got it to work. Going to close this issue for now as I've created one to track the progress of the launcher.

**Closed as completed by ukgamer** 2021-01-27 00:01 UTC

**Comment by sword134** [comment] 2021-01-27 00:08
@ukgamer one last thing though. Spawning it in via the script creates a horrendous model. Spawning it in via the entity spawn list is normal but with the script its half invisible

**Comment by ukgamer** [comment] 2021-01-27 00:24
Which game was this? Does it still happen if you clear the cache and reload the machines using the context menu? I think sometimes custom cabinet art fails to load properly for some reason, I've not been able to reproduce it myself.

**Comment by sword134** [comment] 2021-01-27 00:36
@ukgamer copy-paste of the code I provided earlier. So asteroids. I don't have the option to reload the machine from the context menu apparently (addon perhaps?).

**Comment by ukgamer** [comment] 2021-01-27 00:39
It should appear in the icons on the top left of the context menu (when you hold C) - that will open a settings dialog, or you can use arcade_cabinet_clear_cache  and arcade_cabinet_reload in console.

**Comment by sword134** [comment] 2021-01-27 00:43
@ukgamer clearing cache and reloading did nothing unfortunately.

**Comment by sword134** [comment] 2021-01-27 00:44
Perhaps the solution is to just make a cabinet entity for every game? That way you can also use permaprops and don't have to go the entire scripted lua route.

**Comment by ukgamer** [comment] 2021-01-27 01:36
Are you on the Chromium branch of GMod? I just debugged this with another person who was having the same issue - turns out he was on the Chromium branch (which is outdated and should not be used). He changed to the x86-64 branch and the issue was resolved. It should also work in normal GMod.

**Comment by sword134** [comment] 2021-01-27 11:42
@ukgamer No I am not using any special beta branches for gmod.

**Comment by sword134** [comment] 2021-01-27 12:33
![20210127133301_1](https://user-images.githubusercontent.com/14058522/105991564-3b41c080-60a4-11eb-8c66-3fb8905ba50b.jpg)
So I spawned in all the the arcade machines. And it seems like it only some that have the texture problem for example asteroids.

**Comment by ukgamer** [comment] 2021-01-27 13:06
It looks like there is some issue with how GMod creates the material for the custom cabinet art that doesn't affect the 64 bit branch. I will have a look later to see if I can work around this until 64 bit becomes the main branch, but it may be that I just end up disabling custom cabinet art on this version of GMod.

**Comment by ukgamer** [comment] 2021-01-27 19:22
A GMod update dropped today that fixes the material issue. I've confirmed cabinet art is now working after switching to the default branch.

https://gmod.facepunch.com/blog/january-2021-update

**Comment by sword134** [comment] 2021-01-27 19:37
@ukgamer thats very convenient and yes it has indeed fixed the issue!
